# Generated by Django 2.2.4 on 2020-10-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('eventType', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('links', models.CharField(max_length=5000)),
                ('twitter', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='nasa',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
